# Configuración de Mosquitto MQTT con Autenticación Dinámica por HTTP
listener 1883 0.0.0.0
allow_anonymous false

# Habilitar el plugin de autenticación en Go
auth_plugin /mosquitto/go-auth.so

# Definir que usaremos el backend 'http'
auth_opt_backends http

# Host y puerto del Backend Express (dentro de la red de Docker)
auth_opt_http_host backend
auth_opt_http_port 3000

# Endpoints de validación en el Backend
auth_opt_http_getuser_uri /api/v1/mqtt/autenticar
auth_opt_http_superuser_uri /api/v1/mqtt/superusuario
auth_opt_http_aclcheck_uri /api/v1/mqtt/acl

# Envío de parámetros por método POST
auth_opt_http_with_tls false

# Configuración básica de Mosquitto (Persistencia y Logs)
persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S
